function Yo() {
    const t = [
        "7058265snUKCd",
        "7980yEPyMo",
        "thm_rmt.form.admin.main.button.announcement",
        "thm_rmt.form.admin.main.button.adminClaimFlag",
        "1220664HUhlFb",
        "83208BnDZWt",
        "thm_rmt.message.adminClaimFlag.alreadyHave",
        "thm_rmt.form.admin.main.title",
        "giveItem",
        "overworld",
        "7374656XWsKov",
        "Back",
        "selection",
        "thm_rmt.form.admin.main.body.announcements",
        "Edit Announcements",
        "thm_rmt.form.admin.main.body.ranks",
        "MENU_RANKS",
        "admin",
        "10255602VQUsjY",
        "getClaimData",
        "sendSuccessMsg",
        "sendErrorMsg",
        "ADMIN_CLAIM",
        "button",
        "Settings",
        "thm_rmt.form.admin.main.button.settings",
        "thm_rmt.form.admin.main.body.spawn",
        "canceled",
        "show",
        "Manage Players",
        "push",
        "thm_rmt.form.admin.main.body.world",
        "hasItem",
        "Manage Warps",
        "ANNOUNCEMENT",
        "SETTINGS",
        "224646UNudfP",
        "Give Admin Flag",
        "nether",
        "thm_rmt.form.admin.main.button.manageWarps",
        "claims",
        "Menu",
        "ADMIN_CLAIM_FLAG",
        "thm_rmt.form.admin.main.body.menu",
        "Manage World",
        "thm_rmt.form.admin.main.button.manageSpawn",
        "length",
        "thm_rmt.form.admin.main.body.settings",
        "rawtext",
        "thm_rmt.form.admin.main.body.warps",
        "thm_rmt.form.button.back",
        "thm_rmt.form.admin.main.button.managePlayers",
        "thm_rmt.message.adminClaimFlag.give",
        "theEnd",
        "thm_rmt.form.admin.main.button.menu",
        "MENU_PROFILE",
        "Manage Spawn",
        "thm_rmt.form.admin.main.body",
        "Manage Ranks",
        "133bLpbNT",
    ];
    return (Yo = function () {
        return t;
    })();
}